"""empty message

Revision ID: d59f6381bfb7
Revises: None
Create Date: 2016-05-02 15:40:16.235656

"""

# revision identifiers, used by Alembic.
revision = 'd59f6381bfb7'
down_revision = None

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('model_grids',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('grid', postgresql.JSONB(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('model_grids')
    ### end Alembic commands ###
